apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  username: cG9zdGdyZXM=  # postgres in base64
  password: cG9zdGdyZXM=  # postgres in base64
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  secret: eW91ci1zZWNyZXQta2V5  # your-secret-key in base64
